
environment:
  matrix:
    - vs_version: 15

os: Visual Studio 2017

configuration:
  - release
  - debug

platform:
  - x64

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - curl -LO https://downloads.sourceforge.net/project/scons/scons-local/3.0.5/scons-local-3.0.5.zip
  - unzip scons-local-3.0.5.zip
  - ./build_libs.bat %configuration%
  - scons platform=windows target=%configuration% -j6
